apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-crm
  namespace: default
  labels:
    app: demo-crm
spec:
  replicas: {{ .Values.demoCrm.replicasCount }}
  selector:
    matchLabels:
      app: demo-crm
  template:
    metadata:
      labels:
        app: demo-crm
    spec:
      containers:
      - name: demo-crm
        image: {{ .Values.demoCrm.imageName }}
        ports:
        - containerPort: {{ .Values.demoCrm.appPort }}
        envFrom:
          - configMapRef:
              name: demo-configmap
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-demo-crm
  namespace: default
  labels:
    app: demo-crm
spec:
  type: ClusterIP
  selector:
    app: demo-crm
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.demoCrm.appPort }}