apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-crm
  namespace: default
  labels:
    app: demo-crm
spec:
  replicas: {{ .Values.demoCrm.replicasCount }}
  selector:
    matchLabels:
      app: demo-crm
  template:
    metadata:
      labels:
        app: demo-crm
    spec:
      containers:
      - name: demo-crm
        image: {{ .Values.demoCrm.imageName }}:{{ .Values.demoCrm.imageTag }}
        ports:
        - containerPort: {{ .Values.demoCrm.appPort }}
        envFrom:
          - configMapRef:
              name: demo-configmap
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
