apiVersion: v1
kind: Service
metadata:
  name: clusterip-demo-crm
  labels:
    app: demo-crm
spec:
  type: LoadBalancer
  selector:
    app: demo-crm
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.service.servicePort }}
    targetPort: {{ .Values.service.appPort }}